### ISSUE TITLE
Unable to access image url

### ISSUE THREAD

**Issue by lanery** [fcollman/render-python#103]
Hello,
I was progressing through the documentation and having success until I wanted to visualize my image tile. I run the script
```py
import renderapi
from renderapi.layout import Layout
from renderapi.transform import AffineModel
from renderapi.tilespec import TileSpec


# Create a renderapi.connect.Render object
render_connect_params = {
    'host': 'localhost',
    'port': 8080,
    'owner': 'myowner',
    'project': 'myproject',
    'client_scripts': \
        '/usr/local/render/render-ws-java-client/src/main/scripts',
    'memGB': '2G'
}

render = renderapi.connect(**render_connect_params)

# Make a new stack
stack = 'mystack'
renderapi.stack.create_stack(stack,render=render)

# Define a tile layout
layout = Layout(sectionId='1',
                scopeId='myscope',
                cameraId='mycamera',
                imageRow=0,
                imageCol=0,
                stageX=100.0,
                stageY=300.0,
                rotation=0.0,
                pixelsize=3.0)

# Define a simple transformation, here a translation based upon layout
at = AffineModel(B0=layout.stageX/layout.pixelsize,
                 B1=layout.stageY/layout.pixelsize)

# Define a tile
tilespec = TileSpec(tileId='000000000000',
                    z=0.0,
                    width=2048,
                    height=2048,
                    imageUrl='file:/home/rlane/development/pancrea/images/pancrea9-0x0.tiff',
                    maskUrl=None,
                    layout=layout,
                    tforms=[at])

# Use the simple non-parallelized upload option
renderapi.client.import_tilespecs(stack,
                                  [tilespec],
                                  render=render)

# Now close the stack
renderapi.stack.set_stack_state(stack, 'COMPLETE', render=render)
```
which outputs 
```
org.janelia.render.client.ImportJsonClient

  Running: /usr/local/render/deploy/jdk1.8.0_131/bin/java -cp /usr/local/render/render-ws-java-client/target/render-ws-java-client-2.0.1-SNAPSHOT-standalone.jar -Xms2G -Xmx2G -Djava.awt.headless=true -XX:+UseSerialGC org.janelia.render.client.ImportJsonClient --baseDataUrl http://localhost:8080/render-ws/v1 --owner myowner --project myproject --stack mystack /tmp/tmppnr50bsm.json


18:26:43.171 [main] INFO  [org.janelia.render.client.ClientRunner] run: entry
18:26:43.320 [main] INFO  [org.janelia.render.client.ImportJsonClient] runClient: entry, parameters={
  "renderWeb" : {
    "baseDataUrl" : "http://localhost:8080/render-ws/v1",
    "owner" : "myowner",
    "project" : "myproject"
  },
  "tileSpecValidator" : { },
  "stack" : "mystack",
  "tileFiles" : [
    "/tmp/tmppnr50bsm.json"
  ]
}
18:26:43.576 [main] INFO  [org.janelia.render.client.RenderDataClient] getStackMetaData: submitting GET http://localhost:8080/render-ws/v1/owner/myowner/project/myproject/stack/mystack
18:26:43.662 [main] INFO  [org.janelia.render.client.RenderDataClient] ensureStackIsInLoadingState: mystack stack is already in the LOADING state
18:26:43.663 [main] INFO  [org.janelia.render.client.ImportJsonClient] loadTransformData: exit, loaded 0 transform specs
18:26:43.663 [main] INFO  [org.janelia.render.client.ImportJsonClient] importStackData: entry, tileFile=/tmp/tmppnr50bsm.json
18:26:43.663 [main] INFO  [org.janelia.render.client.ImportJsonClient] loadTileData: entry, path=/tmp/tmppnr50bsm.json
18:26:43.693 [main] INFO  [org.janelia.render.client.ImportJsonClient] loadTileData: exit, loaded 1 tile specs
18:26:43.708 [main] INFO  [org.janelia.render.client.ImportJsonClient] importStackData: derived bounding box for 1 tiles, elapsedSeconds=0
18:26:43.729 [main] INFO  [org.janelia.render.client.RenderDataClient] saveResolvedTiles: submitting PUT http://localhost:8080/render-ws/v1/owner/myowner/project/myproject/stack/mystack/resolvedTiles for 0 transforms and 1 tiles
18:26:43.737 [main] INFO  [org.janelia.render.client.ImportJsonClient] importStackData: exit, saved tiles and transforms from /tmp/tmppnr50bsm.json
18:26:43.737 [main] INFO  [org.janelia.render.client.ClientRunner] run: exit, processing completed in 0 hours, 0 minutes, 0 seconds
```
to the terminal, which all looks good to me. But when I try to access the url to the rendered image tile:
http://localhost:8080/render-ws/v1/owner/myowner/project/myproject/stack/mystack/z/0/tiff-image
I get the message:
`failed to retrieve {url: 'file:/home/rlane/development/pancrea/images/pancrea9-0x0.tiff', downSampleLevels: 6, isMask: false, convertTo16Bit:true} from cache`.

I have the file `pancrea9-0x0.tiff` in `/home/rlane/development/pancrea/images/`.

I searched the documentation for more information on actually displaying the rendered images either dynamically, via CATMAID, or via NdViz but couldn't really find anything. Thank you for any help you are able to offer.

**Comment by fcollman** [comment]
Hi so this probably has to do with the manner in which you are deploying render.  When you ask render to do server side rendering (such as with the call to tiff-image) the server needs to have access to the file paths that are referenced in the tilespec json files.  In this case, your image data is at /home/rlane/development/pancrea/images/.  If the server process that is running render doesn't have access to that location then render can't read the image.  This could be for a few reasons.

If you are running it on a remote server, maybe /home/rlane is local only to the client machine you uploaded the tilespecs form.

If you are running it locally, but within say docker, you may not have volume mounted in the mount points where you have your data. 

If you describe your render deployment in more detail I might have some more ideas..

**Comment by lanery** [comment]
Thank you for your quick response. To install render I essentially just followed the steps here https://github.com/saalfeldlab/render/blob/master/docs/src/site/markdown/render-ws.md
I then started jetty and followed the example https://github.com/saalfeldlab/render/blob/master/docs/src/site/markdown/render-ws-example.md
which all ran fine and I was able to see the rendered images at the given links.

After installing render-python, I moved render to /usr/local.
I am running everything locally and I did not use docker. Sorry if this is not a sufficient description of my render deployment -- I am happy to provide more info, but am not sure how to expand on my deployment better.

**Comment by RussTorres** [comment]
If you followed the render-ws deploy documentation, some more detailed information might be found in the serverside jetty logs at `<render_path>/deploy/jetty_base/logs/...` . These can sometimes illuminate issues in things like permissions.
Although I don't think it would cause this error, the script you provided is not specifying a minimum or maximum intensity, and the tilespec defaults to working with 16-bit images -- does this work for your data?

**Comment by lanery** [comment]
Thanks for the additional info Russel, but I think the issue came down to 1) `tiff` (bad) vs `tif` (good) for the file extension and 2) `/tiff-image` (bad) vs `/jpeg-image` (good) for the end of the url. I messed around with a bunch of stuff this week so it's hard to say that this was the only difference, but I can say that if I run my script with this block
```
# Define a tile
tilespec = TileSpec(tileId='000000000000',
                    z=0.0,
                    width=2048,
                    height=2048,
                    imageUrl='file:/opt/tiles/pancrea2/pancrea9-0x0.tiff',
                    maskUrl=None,
                    layout=layout,
                    tforms=[at])
```
and go to http://localhost:8080/render-ws/v1/owner/myowner/project/myproject/stack/mystack/z/0/box/0,0,5000,5000,0.5/jpeg-image I get the same error message as before (now with a different number of downSampleLevels for some reason). But simply changing the extension from `tiff` to `tif` returns a nicely rendered image at the same url. I should note that I have both `pancrea9-0x0.tiff` and `pancrea9-0x0.tif` at `/opt/tiles/pancrea2/` and that the images are identical -- I literally just changed the extension. Also my data is 16-bit.

Finally, I just wanted to add that I really appreciate you and your team writing a python api for render and EM_aligner. I will likely be submitting future issues as I still find the whole ecosystem of tools to be as complicated as they are cool.
