### ISSUE TITLE
Unable to Change Tile Placement Order within Stack

### ISSUE THREAD

**Issue by lanery** [fcollman/render-python#106]
Hello,

As you can see in the below image, I have severe contrast differences in the overlapping regions between tiles. I would like to essentially hide the overlapping region by simply reordering the order in which tiles are rendered. For example, in the below image, the 2nd and 4th rows are in the order I would like, and I would like to reverse the order in the 1st, 3rd, and 5th row.

I tried doing this by changing the order of tilespecs in my call to `renderapi.client.import_tilespecs`, but no matter what the order is, it seems to render the tiles in the same order. Is there a way to reorder the tile placement to display certain tiles on top of one another? Thanks.

![image](https://user-images.githubusercontent.com/8359342/41107641-0a392b38-6a73-11e8-9450-a6bed083ff41.png)

**Comment by RussTorres** [comment]
Render has a setting which can change the order in which tiles overlay each other.  In the default configuration tilespecs meant to be on "top" should have lexigraphically greater tileIds than the tiles they overlay.  e.g. 'tile_123b' would be seen on top of 'tile_123a', in turn on top of 'tile_122a'.

**Comment by fcollman** [comment]
Right now no there is not. However you can set masks individually by tile that will control the blending with much more control. I see you have a bleaching artifact you would like to minimize. I would suggest either two masks for a leftward vs rightward tile, or creating a custom one for each mosaic layout based upon the tiles that overlap and were taken before in time. I use the shapely library to do this in python. I’ll find a link to some related code to help you

**Comment by lanery** [comment]
The masking option sounds hopeful and some sample code would be great. Thanks again to the both of you

**Comment by fcollman** [comment]
Here's the function to convert a tilespec to a shapely geometry (assuming all your transforms have .tform implemented).

https://github.com/fcollman/render-python-apps/blob/develop/renderapps/shapely/__init__.py

Here's some example code that is using that function to help figure out which tile most overlaps with which tile between two stacks.

https://github.com/fcollman/render-python-apps/blob/master/renderapps/registration/find_principal_tile_overlaps.py

**Comment by fcollman** [comment]
can we close this issue @lanery ?

**Comment by lanery** [comment]
While I still haven't gotten around to actually implementing the masks yet, I am fine closing the issue. Thanks again for the help.
