### ISSUE TITLE
client.import_tilespecs_parallel unstable for programs that call it multiple times

### ISSUE THREAD

**Issue by fcollman** [fcollman/render-python#14]
I had a bug where using import_tilespecs_parallel multiple times in the same python program was failing the second time i used it.  My program was also using pathos pool for another process, which worked the first 2 times...

so structure is

pool.map()
pool.close()
pool.join()
import_tilespecs_parallel
pool.map()
pool.close()
pool.join()
import_tilespecs_parallel <<< FAIL!

but replacing it with non parallel import it worked fine

**Comment by RussTorres** [comment]
Commit pushed to develop.  If you can confirm that this commit fixes it, we should add to master and close this issue.

**Comment by fcollman** [comment]
I believe this issue has now been resolved with the latest commits and i'm merging to master once it passes.
