### ISSUE TITLE
Support for Rigid, Similarity, Translation Models

### ISSUE THREAD

**Issue by RussTorres** [fcollman/render-python#15]
It would be straightforward to port some of the AffineModel framework to a base HomographyTransform class and extend that to allow Rigid, Similarity, and Translation transforms to be represented in the transform module.  While to my knowledge EM_aligner does not implement these models, it could be helpful for trakem2-assisted workflows.

**Comment by fcollman** [comment]
For the EM aligned reason I might advocate for allowing these on render python side, but writing them as AffineModels to render until such time as that support is more pervasive
