### ISSUE TITLE
Race condition on multiple client uploads specifying same ReferenceTransform

### ISSUE THREAD

**Issue by RussTorres** [fcollman/render-python#30]
This may be better worked around in Render than in this repo, but it does affect some of the parallelization and testing efforts.

We have been getting sporadic errors (BulkWriteError message) when trying to transfer tiles using a client paired with multiprocessing .  This may be a race condition that does not allow multiple client uploads which define the same transformation as a reference for the mongoDB.  This has led to failed tests which are ameliorated by #29, but may still cause an issue in testing and production.

**Comment by fcollman** [comment]
Eric Trautman thinks this was a bug in Mongo that he fixed in render here..

https://github.com/saalfeldlab/render/commit/db2bd32b12cad6d827cf800cd907f202477f7592

i'm trying to sync our fork/branch of render with janelia's and test that all is well..

**Comment by fcollman** [comment]
I think that this issue is actually fixed now and was in render.
