### ISSUE TITLE
non-object returned by renderapi.stack.get_stack_bounds

### ISSUE THREAD

**Issue by djkapner** [fcollman/render-python#31]
Why does this call return a dict rather than an object?

```
In [34]: rc=renderapi.stack.get_stack_bounds(source_stack,render=render,owner='gayathri')

In [35]: rc
Out[35]: 
{u'maxX': 243727.0,
 u'maxY': 1017867.0,
 u'maxZ': 3483.0,
 u'minX': -2646.0,
 u'minY': -3099.0,
 u'minZ': 2266.0}

In [36]: rc['minX']
Out[36]: -2646.0
```
for example, tilespec returns objects

```
In [37]: rcinter=renderapi.tilespec.get_tile_specs_from_z(source_stack,z,render=render,owner='gayathri')

In [38]: len(rcinter)
Out[38]: 282

In [40]: rcinter[0].minX
Out[40]: 74613.0
```

**Comment by fcollman** [comment]
So this is presently intended, in that we have not constructed formal python objects for all types of returns types from render.  Usually we wait till we have some need to run a common method on such a return before we implement an object.  For example, recently I implemented an object for resolvedTiles returns.  We could implement a Bounds object, with minX, minY, maxX, maxY properties, but we just haven't done that yet.  One quick hack would be to follow this pattern if you want a namespace.

https://stackoverflow.com/questions/2597278/python-load-variables-in-a-dict-into-namespace

**Comment by RussTorres** [comment]
off-topic: I think that `get_stack_bounds` is dependent on the the state of the stack while `get_section_bounds` is not.  If people are using this functionality it might be helpful to have an implementation of `get_stack_bounds` that does not require server-side aggregate statistics to be calculated.

**Comment by djkapner** [comment]
fair enough, it's easy to handle the dict,
