### ISSUE TITLE
Return code handling for requests calls

### ISSUE THREAD

**Issue by RussTorres** [fcollman/render-python#67]
Not all requests calls are raising errors (specifically `RenderError`s) when exiting unsuccessfully.  One example is `renderapi.stack.delete_section`, but I am suspicious of all `get` and `delete` calls.

**Comment by fcollman** [comment]
Russel and I discussed this the other day... plan is as follows.

step 1) make a standard wrapper for get, post, and delete.
step 2) raise RenderError when there is an exception in the http call, or when the http call returns an error code.
