### ISSUE TITLE
Poor performance on requests returning json

### ISSUE THREAD

**Issue by RussTorres** [fcollman/render-python#78]
We have had significant slowdowns relative to the java webservice in using `requests.get(url).json()`.  Investigations show that performance can be improved by, e.g., setting requests to streaming and changing decode implementation.

**Comment by fcollman** [comment]
So with #91 in place, we now have a singular wrapped place to swap in different json parsers and test their performance. One idea that @RussTorres  had was to have cascading try/except loop imports of json decoders in order of their speed.... however we aren't sure what the speed tradeoff are here for those options (ujson, simplejson, json, requests.json()) etc.  We need to do an experiment to determine what is fastest.
