### ISSUE TITLE
NonLinearCoordinateTransform transformId deserialization bug

### ISSUE THREAD

**Issue by RussTorres** [fcollman/render-python#81]
A good fix for this would probably also resolve #80, but documenting separately while I think about that.  The current implementation of `renderapi.transform.NonLinearCoordinateTransform` will, when given a json dictionary, load the proper attributes and then overwrite transformId with the argument value (default `None`).  This is problematic for dereferencing transformations and probably should have a test.

**Comment by fcollman** [comment]
resolved with #83
